docker/dockerfile-build-ubuntu-16.04, docker/dockerfile-hipblas-ubuntu-16.04
Test install of hipblas with apt-get so dependencies automatically
download with apt tool
=> install hipblas with apt-get

clients/common/hipblas_template_specialization.cpp, clients/gtest/CMakeLists.txt, clients/gtest/gemm_strided_batched_gtest.cpp, clients/include/hipblas.hpp, clients/include/testing_gemm_strided_batched.hpp, library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp
adding library functions and test code for strided - batched [sd]gemm
=> adding hipblasSgemmStridedBatched and hipblasDgemmStridedBatched

library/src/CMakeLists.txt
hipblas /develop branch targets rocblas /develop branch
=> Add the appropriate namespace export to link rocblas

.gitignore, CMakeLists.txt, clients/gtest/CMakeLists.txt, install.sh, library/src/CMakeLists.txt, library/src/nvcc_detail/hipblas.cpp
*  Adding parameter to install.sh to build for cuda backend
*  Adding a few missing CUDA marshalling routines
=> Fixes to build for CUDA backend

install.sh
Avoid using sudo command if already root, that way dockerfiles do
not need to install the sudo command
=> Adding logic in install.sh script to detect root user

CMakeLists.txt, clients/CMakeLists.txt, clients/samples/CMakeLists.txt, clients/samples/example_sgemm.cpp, clients/samples/example_sgemm_strided_batched.cpp, clients/samples/example_sscal.cpp, install.sh
Add samples for sscal, sgemm, and sgemmStridedBatched
=> add samples for sscal, sgemm. sgemmStridedBatched

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> add CONTRIBUTING.md files from rocBLAS

CMakeLists.txt
Bump version of develop branch to 0.7.0.0
=> bump develop version to 0.7.0.0

clients/common/hipblas_template_specialization.cpp, clients/gtest/CMakeLists.txt, clients/gtest/geam_gtest.cpp, clients/include/hipblas.hpp, clients/include/testing_geam.hpp, clients/include/testing_gemm.hpp, library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp, library/src/nvcc_detail/hipblas.cpp
Add geam code and tests to hcc and nvcc
=> adding geam code and tests

clients/include/testing_asum.hpp, clients/include/testing_dot.hpp, clients/include/testing_iamax.hpp, clients/samples/CMakeLists.txt, clients/samples/example_sgemm.cpp, clients/samples/example_sgemm_strided_batched.cpp, clients/samples/example_sscal.cpp
correct build error in samples
=> fix nvcc build for samples

clients/include/testing_iamax.hpp
=> correct iXamax tests to 1 based indexing

README.md
=> correct link for build and supported functions

clients/common/arg_check.cpp, clients/common/hipblas_template_specialization.cpp, clients/gtest/CMakeLists.txt, clients/gtest/gemm_batched_gtest.cpp, clients/gtest/ger_gtest.cpp, clients/include/arg_check.h, clients/include/hipblas.hpp, clients/include/testing_gemm_batched.hpp, clients/include/utility.h, library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp, library/src/nvcc_detail/hipblas.cpp
Add hipblasXgemmBatched. This is a loop to hipblasXgemm for batch_count times. Performance optimizations can be added in the future.
=> adding hipblasXgemmaBatched

clients/gtest/geam_gtest.cpp, clients/include/hipblas_unique_ptr.hpp, clients/include/testing_geam.hpp
fix error in geam tests, and add back geam tests
=> fix geam tests

CMakeLists.txt
=> add NO_GIT_TAG_VERSION to remove sha in build name

clients/common/hipblas_template_specialization.cpp, clients/gtest/blas1_gtest.cpp, clients/include/testing_nrm2.hpp, library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp, library/src/nvcc_detail/hipblas.cpp
nrm2 functions were missing (required for iterative solvers)
=> added hipblas<T>nrm2()

install.sh
=> Add RHEL 7 support

clients/common/cblas_interface.cpp, clients/common/unit.cpp, clients/gtest/CMakeLists.txt, clients/gtest/gemm_ex_gtest.cpp, clients/include/testing_gemm_ex.hpp, clients/include/utility.h, library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp
add mixed precision hipblasGemmEx to hcc_detail. Still needs to be added to nvcc_detail.
=> add hipblasGemmEx

install.sh
-  add -y to yum localinstall to eliminate manual intervention
-  add --nogpgcheck to yum install to avoid failure when installing from unsigned repo
=> make yum *install smoother

library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp, library/src/nvcc_detail/hipblas.cpp
-  parameter A and B of hipblas gemm should be declared as const. This patch corrects type of hipblasHgemm's parameter A and parameter B
=> Correct type of hipblasHgemm's parameters.

clients/gtest/geam_gtest.cpp
=> correct geam ldc bug

.clang-format, .githooks/pre-commit, Jenkinsfile, clients/common/norm.cpp, clients/gtest/blas1_gtest.cpp, clients/gtest/geam_gtest.cpp, clients/gtest/gemm_batched_gtest.cpp, clients/gtest/gemm_ex_gtest.cpp, clients/gtest/gemm_gtest.cpp, clients/gtest/gemm_strided_batched_gtest.cpp, clients/gtest/gemv_gtest.cpp, clients/gtest/ger_gtest.cpp, clients/gtest/set_get_matrix_gtest.cpp, clients/gtest/set_get_vector_gtest.cpp, clients/gtest/trsm_gtest.cpp, clients/gtest/trtri_gtest.cpp, clients/include/hipblas_unique_ptr.hpp, clients/include/testing_gemm_batched.hpp, clients/include/testing_gemm_ex.hpp, clients/include/testing_nrm2.hpp, docker/dockerfile-build-centos, docker/dockerfile-build-ubuntu-rock, docker/dockerfile-install-centos, install.sh
- Also ran clang-format through repo and added new .clang-format file
=> Added hip-clang and centos jenkins jobs

CMakeLists.txt, library/CMakeLists.txt
=> Updating version with new rocm-cmake standard

CMakeLists.txt, library/src/CMakeLists.txt
I don't know the best way to do this. This is an option for you.
=> Hot fix for versioning

CMakeLists.txt
Standardizing library version to follow new standards. There should be 3 sets of numbers only.
=> Standardizing library versions

install.sh
- See PR #104
- I created a new branch due to commit history differences between master and develop
=> Removing hip-clang install script artifacts

CMakeLists.txt, install.sh
I do not know how to safely merge develop into master. I am doing the SLES support this way to avoid any issues.
=> SLES support cherry-pick

.clang-format
This fixed the format check issue with rocBLAS
=> Added clang10-format option to format file

CMakeLists.txt, bump_develop_version.sh, bump_master_version.sh, clients/gtest/CMakeLists.txt, clients/samples/CMakeLists.txt
=> ROCm2.10 merge master into develop

CMakeLists.txt, bump_develop_version.sh, bump_master_version.sh
- develop branch hipBLAS version is 0.19.0
=> merge master into develop for ROCm 3.0

clients/common/cblas_interface.cpp, clients/common/flops.cpp, clients/common/hipblas_template_specialization.cpp, clients/common/near.cpp, clients/common/norm.cpp, clients/common/unit.cpp, clients/common/utility.cpp, clients/gtest/blas1_gtest.cpp, clients/gtest/gemm_batched_gtest.cpp, clients/gtest/gemm_gtest.cpp, clients/gtest/gemm_strided_batched_gtest.cpp, clients/gtest/gemv_batched_gtest.cpp, clients/gtest/gemv_gtest.cpp, clients/gtest/gemv_strided_batched_gtest.cpp, clients/include/testing_nrm2.hpp, clients/include/testing_nrm2_batched.hpp, clients/include/testing_nrm2_strided_batched.hpp, clients/include/utility.h, library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp, library/src/nvcc_detail/hipblas.cpp
Same as PR #137, but for master, as per [SWDEV-216797](http://ontrack-internal.amd.com/browse/SWDEV-216797)
Go ahead and merge it if you approve.
=> hipComplex -> hipblasComplex, hipDoubleComplex -> hipblasDoubleComplex

library/include/hipblas-version.h.in
This should fix #134. Came across this issue here (https://github.com/ginkgo-project/ginkgo/pull/373#discussion_r346530665) while looking to update hipblas to match rocblas.
Doesn't seem too urgent so can be delayed to 3.2 if desired.
=> Hipblasversionbug

clients/gtest/CMakeLists.txt, install.sh, library/CMakeLists.txt
This applies the hot fix that was added from the master branch to the develop branch
=> Merging hip-clang fixes (#147)

CMakeLists.txt, library/CMakeLists.txt, library/include/hipblas-version.h.in
- added more gpu targets
- updated maintainer info
- added protection in header file in case circular including
=> minor fixes

docker/dockerfile-build-centos, docker/dockerfile-build-fedora, docker/dockerfile-build-nvidia-cuda, docker/dockerfile-build-ubuntu, docker/dockerfile-build-ubuntu-rock, docker/dockerfile-install-centos, docker/dockerfile-install-fedora, docker/dockerfile-install-nvidia-cuda, docker/dockerfile-install-ubuntu
correction: use hipblas-maintainer, not rocblas-maintainer
=> use hipblas-maintainer not rocblas-maintainer

CMakeLists.txt, bump_develop_version.sh, bump_master_version.sh
=> ROCm 3.3 feature complete merge master into develop

CMakeLists.txt, clients/gtest/CMakeLists.txt, clients/samples/CMakeLists.txt, library/src/CMakeLists.txt
=> Fix hip target to be compatible with hip-clang (#167)

CMakeLists.txt, bump_develop_version.sh, bump_master_version.sh, clients/samples/CMakeLists.txt, install.sh, library/src/CMakeLists.txt
Reverts ROCmSoftwarePlatform/hipBLAS#181
=> Revert "Merge master into develop for ROCm 3.4"

CMakeLists.txt, bump_develop_version.sh, bump_master_version.sh, clients/samples/CMakeLists.txt, install.sh
Reverts ROCmSoftwarePlatform/hipBLAS#185
=> Revert "ROCm 3.4 Feature Complete Merge master into develop"

.jenkins/common.groovy
Dockerfile is not enabling properly, enabling right before build command.
=> Enable devtoolset7 in CentOS CI

clients/include/utility.h, library/include/hipblas.h
=> Make constexpr variable template static, to satisfy ODR

library/include/hipblas.h
=> Document workaround, since it's not obvious and will probably raise questions later

install.sh
cherrypick into master-rocm-3.5
=> Add dependencies for centos 8

clients/gtest/CMakeLists.txt
* fixes cuda compilation
Co-authored-by: carlushuang <carlushuang@hotmail.com>
=> add compile flags for nvcc

clients/gtest/set_get_matrix_gtest.cpp, clients/gtest/set_get_vector_gtest.cpp, clients/include/hipblas_fortran.f90, clients/include/hipblas_fortran.hpp, clients/include/testing_set_get_matrix_async.hpp, clients/include/testing_set_get_vector.hpp, clients/include/testing_set_get_vector_async.hpp, library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp, library/src/hipblas_module.f90, library/src/nvcc_detail/hipblas.cpp
[SWDEV-232444](http://ontrack-internal.amd.com/browse/SWDEV-232444).
Adds:
- hipblasGetVectorAsync
- hipblasSetVectorAsync
- hipblasGetMatrixAsync
- hipblasSetMatrixAsync
Also adds Fortran tests for Get/Set Vector/Matrix functions.
I see some format updates were added here too.
=> Adding async functions

.jenkins/common.groovy, .jenkins/staticlibrary.groovy
=> Add static lib build to CI

.jenkins/precheckin.groovy
=> Add gfx908 back to precheckin CI

CMakeLists.txt
* Fortran compiler consistent with rocBLAS
=> default fortran compiler to match rocBLAS and rocSOLVER

.githooks/pre-commit, .jenkins/common.groovy, .jenkins/multicompiler.groovy, .jenkins/precheckin.groovy, .jenkins/staticanalysis.groovy, .jenkins/staticlibrary.groovy, LICENSE.md, clients/gtest/blas1_gtest.cpp, clients/gtest/hipblas_gtest_main.cpp, clients/include/hipblas_vector.hpp, library/src/hcc_detail/hipblas.cpp
This needs to pick up the correct rocBLAS and rocSOLVER before the CI tests will work.
=>  Make device memory reallocate on demand in hipBLAS

CMakeLists.txt, install.sh
* don't try and find cuda if not using it
=> ignore cuda if not passed --cuda

library/CMakeLists.txt
- Resolves some of the Lintian errors in SWDEV-248139
- Other Lintian errors will need to be resolved in rocm-cmake
=> Resolve some Lintian errors in package information

.jenkins/multicompiler.groovy
=> Remove clang++ from CI multi-compiler job

.githooks/pre-commit
=> Skip symlinks when reformatting files

clients/benchmarks/client.cpp, clients/include/testing_copy.hpp, clients/include/testing_copy_batched.hpp, clients/include/testing_copy_strided_batched.hpp
=> Added copy to hipblas-bench

clients/common/cblas_interface.cpp, clients/gtest/axpy_ex_gtest.cpp, clients/gtest/scal_ex_gtest.cpp, clients/include/cblas_interface.h, clients/include/testing_axpy_batched.hpp, clients/include/testing_axpy_batched_ex.hpp, clients/include/testing_axpy_ex.hpp, clients/include/testing_axpy_strided_batched_ex.hpp, clients/include/testing_scal_batched_ex.hpp, clients/include/testing_scal_ex.hpp, clients/include/testing_scal_strided_batched_ex.hpp, clients/include/type_dispatch.hpp
Adding tests for newly supported rocBLAS types for axpy_ex and scal_ex.
=> Adding tests for axpy_ex and scal_ex

scripts/performance/blas/commandrunner.py, scripts/performance/blas/getspecs.py, scripts/performance/blas/performancereport.py
It appears that rocm_smi.py has changed in a recent release, which broke some of the data-gathering in the script. These have been fixed/worked-around here.
Also fixed some bugs with the --cuda and --compare options.
Going to play around with the script a little more to make sure everything is working as expected.
=> Performance script fixes

clients/benchmarks/client.cpp, clients/include/testing_scal_batched_ex.hpp, clients/include/testing_scal_ex.hpp, clients/include/testing_scal_strided_batched_ex.hpp, clients/include/type_dispatch.hpp
=> Add scal_ex to hipblas-bench

clients/benchmarks/client.cpp, clients/gtest/blas1_gtest.cpp, clients/include/hipblas_vector.hpp, clients/include/norm.h, clients/include/testing_asum.hpp, clients/include/testing_asum_batched.hpp, clients/include/testing_asum_strided_batched.hpp, clients/include/testing_axpy.hpp, clients/include/testing_axpy_batched.hpp, clients/include/testing_axpy_strided_batched.hpp, clients/include/testing_dot.hpp, clients/include/testing_dot_batched.hpp, clients/include/testing_dot_strided_batched.hpp
Trying to incremently add functions to hipblas-bench.
This PR adds:
- dot
- axpy
- asum
and batched variants.
I've also done some cleanup in the testing files, mainly adding device/host tests where missing, using newer batched_vector styles (similar to rocblas tests), updating names to hipBLAS rather than rocBLAS, etc.
=> Bench add 2

CHANGELOG.md, clients/common/utility.cpp, clients/include/testing_gemv.hpp, clients/include/utility.h, library/include/hipblas.h, library/src/CMakeLists.txt, library/src/hipblas_auxiliary.cpp
=> adds statusToString and localHandle

clients/gtest/CMakeLists.txt, clients/gtest/auxiliary_gtest.cpp, clients/gtest/set_get_atomics_mode_gtest.cpp, clients/gtest/set_get_vector_gtest.cpp, clients/include/testing_gemv_batched.hpp, clients/include/testing_gemv_strided_batched.hpp, clients/include/utility.h
* finishes updates to gemv started in earlier PR and fixes up macros
* ready for widespread reuse
=> gemv use localhandle and fix error macros

clients/gtest/auxiliary_gtest.cpp, clients/include/testing_asum.hpp, clients/include/testing_asum_batched.hpp, clients/include/testing_asum_strided_batched.hpp, clients/include/testing_axpy.hpp, clients/include/testing_axpy_batched.hpp, clients/include/testing_axpy_strided_batched.hpp, clients/include/testing_copy.hpp, clients/include/testing_copy_batched.hpp, clients/include/testing_copy_strided_batched.hpp, clients/include/testing_dot.hpp, clients/include/testing_dot_batched.hpp, clients/include/testing_dot_strided_batched.hpp, clients/include/testing_scal.hpp, clients/include/testing_scal_batched.hpp, clients/include/testing_scal_strided_batched.hpp, clients/include/testing_swap.hpp, clients/include/testing_swap_batched.hpp, clients/include/testing_swap_strided_batched.hpp
Using new hipblas handle for L1 tests. Some other code cleanup has been included here too. All other L1 functions have already been done, or will be done while being added to hipblas-bench.
=> Cleanup for asum, axpy, dot, scal, swap tests.

CMakeLists.txt
See [hipSOLVER 13](https://github.com/ROCmSoftwarePlatform/hipSOLVER/pull/13) and brief discussion in rocBLAS Teams channel.
=> Remove AMDGPU_TARGETS

clients/common/blis_interface.cpp, toolchain-windows.cmake
See https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/pull/800
=> static blis usage

clients/gtest/axpy_ex_gtest.cpp, clients/gtest/blas1_gtest.cpp, clients/gtest/gemm_batched_gtest.cpp, clients/gtest/gemm_ex_gtest.cpp, clients/gtest/gemm_gtest.cpp, clients/gtest/gemm_strided_batched_gtest.cpp, clients/gtest/scal_ex_gtest.cpp, clients/gtest/trsm_ex_gtest.cpp, clients/gtest/trsm_gtest.cpp, clients/include/hipblas_arguments.hpp, clients/include/testing_axpy.hpp, clients/include/testing_axpy_batched.hpp, clients/include/testing_axpy_batched_ex.hpp, clients/include/testing_axpy_ex.hpp, clients/include/testing_axpy_strided_batched.hpp, clients/include/testing_axpy_strided_batched_ex.hpp, clients/include/testing_gemm.hpp, clients/include/testing_gemm_batched.hpp, clients/include/testing_gemm_batched_ex.hpp, clients/include/testing_gemm_ex.hpp, clients/include/testing_gemm_strided_batched.hpp, clients/include/testing_gemm_strided_batched_ex.hpp, clients/include/testing_scal.hpp, clients/include/testing_scal_batched.hpp, clients/include/testing_scal_strided_batched.hpp, clients/include/testing_trsm_batched_ex.hpp, clients/include/testing_trsm_ex.hpp, clients/include/testing_trsm_strided_batched_ex.hpp
Adding complex alpha/beta tests/support to axpy, scal, gemm(_ex), trsm(_ex).
=> Adding complex alpha/beta tests

clients/benchmarks/CMakeLists.txt, clients/benchmarks/client.cpp, clients/gtest/geqrf_batched_gtest.cpp, clients/gtest/geqrf_gtest.cpp, clients/gtest/geqrf_strided_batched_gtest.cpp, clients/gtest/getrf_batched_gtest.cpp, clients/gtest/getrf_gtest.cpp, clients/gtest/getrf_strided_batched_gtest.cpp, clients/gtest/getri_batched_gtest.cpp, clients/gtest/getrs_batched_gtest.cpp, clients/gtest/getrs_gtest.cpp, clients/gtest/getrs_strided_batched_gtest.cpp, clients/include/bytes.hpp, clients/include/flops.hpp, clients/include/testing_geqrf.hpp, clients/include/testing_geqrf_batched.hpp, clients/include/testing_geqrf_strided_batched.hpp, clients/include/testing_getrf.hpp, clients/include/testing_getrf_batched.hpp, clients/include/testing_getrf_strided_batched.hpp, clients/include/testing_getri_batched.hpp, clients/include/testing_getrs.hpp, clients/include/testing_getrs_batched.hpp, clients/include/testing_getrs_strided_batched.hpp
Adding rocSOLVER functions to hipblas-bench and cleaning up rocSOLVER tests.
The gflop and gbyte calculations are certainly incorrect, so I would appreciate some help with them :smile:
=> Update solver tests

rmake.py
=> Potential fix for packaging

CHANGELOG.md
Update 4.5 changelog to reflect no 4.4 release
=> Changelog update for ROCm 4.5

clients/samples/CMakeLists.txt, clients/samples/example_hgemm.cpp
Adding a sample of hgemm. This would only be built when using hipcc.
=> hgemm example

library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp, library/src/nvcc_detail/hipblas.cpp
Added doxygen style documentation for level -1 API
converted function arguments to camel case
resolves #___
-
-
-
=> Documentation for BLAS Level-1 APIs

library/include/hipblas.h
Adding documentation for Ex functions
=> Ex documentation

deps/external-gtest.cmake
=> Updating googletest to 1.11.0

install.sh
Ports changes made in https://github.com/ROCmSoftwarePlatform/hipSOLVER/pull/67 to hipBLAS, including adding the cmake-arg parameter and allowing rocblas-path and rocsolver-path to be specified as relative paths.
=> Install script improvements

clients/benchmarks/CMakeLists.txt, clients/gtest/CMakeLists.txt, clients/gtest/gbmv_batched_gtest.cpp, clients/gtest/gbmv_strided_batched_gtest.cpp, clients/gtest/gemv_batched_gtest.cpp, clients/gtest/gemv_strided_batched_gtest.cpp, clients/gtest/geqrf_gtest.cpp, clients/gtest/geqrf_strided_batched_gtest.cpp, clients/gtest/getrf_gtest.cpp, clients/gtest/getrf_strided_batched_gtest.cpp, clients/gtest/getrs_gtest.cpp, clients/gtest/getrs_strided_batched_gtest.cpp, clients/gtest/hemv_batched_gtest.cpp, clients/gtest/hemv_strided_batched_gtest.cpp, clients/gtest/trsm_ex_gtest.cpp, clients/gtest/trtri_gtest.cpp, install.sh
* minimal fixes for address-sanitizer 
* forces lapack deps build to use gfortran
=> force gfortran &  link bench & test for sanitizer

clients/benchmarks/CMakeLists.txt, clients/gtest/CMakeLists.txt, install.sh, library/src/CMakeLists.txt
=> Dev merge master

CHANGELOG.md
Changelog  update for hipBLAS version 0.50
=> changelog update for hipBLAS version 0.50

library/CMakeLists.txt
- Change requested by legal to specify the license type in RPM packages.
=> set RPM license type

clients/benchmarks/client.cpp, clients/gtest/blas1_gtest.cpp, clients/include/hipblas_vector.hpp, clients/include/testing_asum.hpp, clients/include/testing_asum_batched.hpp, clients/include/testing_asum_strided_batched.hpp, clients/include/utility.h
First commit  for adding NaN testing to hipBLAS. Based off the changes in rocBLAS.
=> User-specified initialization for hipblas-bench

library/CMakeLists.txt
Hot fix merge from master into develop
=> Hot fix merge from master into develop

scripts/performance/blas/commandrunner.py, scripts/performance/blas/getspecs.py
=> Updating version gathering info in performance scripts

CHANGELOG.md
Not too many changes to hipBLAS these days.
=> Updating CHANGELOG for ROCm 5.2 feature complete

docs/source/requirements.txt
- Address the hipBLAS documentation build error in readthedocs.
=> Address the readthedocs build failure

clients/CMakeLists.txt, library/src/hcc_detail/hipblas.cpp
resolves #___
- Updated rocblas, rocsolver latest include path 
- Updated build dir include dir path. 
- Fixed internal build warnings from include reorg.
=> Fix include reorg warnings

scripts/performance/blas/commandrunner.py, scripts/performance/blas/performancereport.py
- Adding surface_plot [as done in rocBLAS](https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/pull/841).
- Made some other small changes to make python files more generic as they can be shared between rocBLAS and hipBLAS in the future, or other libraries if applicable. I'm not sure on the future of these in regards to performance measurement vs. the new performance tracking tool in the works, so didn't want to spend too much time on this right now in case we don't need it in the future
=> Adding surface plot to performance scripts

.githooks/pre-commit
- Added '\s' to perl regex to match Copyright string.
=> Minor pre-commit fix

install.sh
- fix for [SWDEV-336664](https://ontrack-internal.amd.com/browse/SWDEV-336664)
=> Cherry pick install.sh fix for RHEL 8 from develop to master

.github/CONTRIBUTING.md, docs/source/contributing.rst
This matches https://github.com/ROCmSoftwarePlatform/rocBLAS/commit/f2a222520963d657be9993a04cfec74609e499dd.
=> Remove CLA from contributing guidelines

.github/CONTRIBUTING.md, docs/source/contributing.rst
- Removes reference to isocpp
- Removes git flow link to match rocblas
- Removes googletest link
=> Removing contributing isocpp reference

clients/benchmarks/client.cpp, clients/common/cblas_interface.cpp, clients/common/hipblas_template_specialization.cpp, clients/gtest/CMakeLists.txt, clients/gtest/gels_gtest.cpp, clients/include/cblas_interface.h, clients/include/flops.hpp, clients/include/hipblas.hpp, clients/include/hipblas_fortran.hpp, clients/include/hipblas_fortran_solver.f90, clients/include/hipblas_no_fortran.hpp, clients/include/testing_gels.hpp, docs/source/functions.rst, library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp, library/src/hipblas_module.f90, library/src/nvcc_detail/hipblas.cpp
Adding hipblasXgels for [SWDEV-344553](https://ontrack-internal.amd.com/browse/SWDEV-344553).
~~Still need to add gflop calculations.~~ Also I'm not familiar with gels so extra review by someone from rocSOLVER in testing_gels.hpp would be appreciated.
Will add batched and stridedbatched variants in another PR, trying to keep them easier to review.
=> Adding hipblasXgels

clients/common/utility.cpp, clients/include/testing_gemm_batched_ex.hpp, clients/include/testing_gemm_ex.hpp, clients/include/testing_gemm_strided_batched_ex.hpp, clients/include/utility.h, docs/source/deprecation.rst, docs/source/usermanual.rst, library/include/hipblas.h, library/src/amd_detail/hipblas.cpp, library/src/hipblas_module.f90, library/src/nvidia_detail/hipblas.cpp
- This PR needs to be merged after rocBLAS PR 1364
- Addresses hipBLAS issue 498 and [LWPMLSE-288](https://ontrack-internal.amd.com/browse/LWPMLSE-288)
- Adds deprecation section to User Guide
=> Allow for int8 datatype selection from hipBLAS

docs/source/conf.py
As per Colin's comment in Teams
=> Updating conf.py copyright date

clients/include/testing_gbmv_strided_batched.hpp, clients/include/testing_sbmv_strided_batched.hpp, clients/include/testing_set_get_matrix_async.hpp, clients/include/testing_set_get_vector_async.hpp, clients/include/testing_spmv_strided_batched.hpp
=> fix some unused-result warnings

clients/benchmarks/client.cpp, clients/common/hipblas_datatype2string.cpp, clients/include/hipblas_datatype2string.hpp, clients/include/testing_exceptions.hpp, library/include/hipblas.h
* adds same fixes as rocblas
* adds datatype invalid enum
=> Lwpmlse 301 unify enum warn

clients/include/hipblas_arguments.hpp
* order needs to match definition
=> fix earlier bad merge

CHANGELOG.md, clients/gtest/hipblas_gtest_main.cpp, docs/source/clients.rst
=> doc updates for yaml

clients/gtest/axpy_ex_gtest.cpp, clients/gtest/dot_ex_gtest.cpp, clients/gtest/nrm2_ex_gtest.cpp, clients/gtest/rot_ex_gtest.cpp, clients/gtest/scal_ex_gtest.cpp
=> update gtest deprecated test_case forms

clients/gtest/CMakeLists.txt
resolves #___
- Updated include path to latest folder structure (ROCM_PATH/include)
-
-
=> Update include path to latest folder structure

CHANGELOG.md
Commits: https://github.com/rocmsoftwareplatform/hipblas/compare/release/rocm-rel-5.4...develop
=> Updating changelog for hipblas 0.54.0

CMakeLists.txt
- This accompanies rocBLAS-internal PR#1702
=> bump required rocBLAS major version number

CHANGELOG.md
@rkamd maybe you can include a point on documentation changes?
=> Changelog for hipBLAS 1.0.0

install.sh, library/include/hipblas.h
Fixes spelling errors noticed while packaging hipblas for Debian.
=> Fix spelling errors

docs/deprecation.rst
* match rocBLAS removal sections, details were in changelog already
=> add removal details

library/src/nvidia_detail/hipblas.cpp
Hotfix PR for #605 to go into 5.7 release-staging branch.
=> Cuda 12 Hotfix
