ROCmSoftwarePlatform/hipBLAS

library/src/CMakeLists.txt
The cmake code fleshed out to search for hip and cuda
dependencies and link into hipblas-nvcc
=> cmake refactoring to for cuda backend

CMakeLists.txt, Jenkinsfile, docker/dockerfile-build-ubuntu-16.04, docker/dockerfile-hipblas-ubuntu-16.04, library/CMakeLists.txt, library/src/CMakeLists.txt
Build libhipblas-hcc.so from librocblas-hcc.so, not from librocblas-hcc.a and libtensile.a. With this change rocBLAS and Tensile are not included in libhipblas-hcc.so. This means that an application using hipblas will need to link to both libhipblas-hcc.so and librocblas-hcc.so.
Also add default configuration options in CMakeList.txt files for the common path.
=> build .so that does not contain hipBLAS

Jenkinsfile, docker/dockerfile-install-hip-hcc-ctu-ubuntu-16.04, docker/dockerfile-install-nvidia-cuda-8, docker/dockerfile-install-rocm-terminal
This enables jenkins to build on 3 platforms
- hcc-ctu (build with latest commits)
- hcc-rocm (released stack)
- cuda
The build will look like it fails, because of known failures on the cuda side.  All unit tests pass on the rocm side.
=> Jenkins fix

Jenkinsfile, docker/dockerfile-build-hip-hcc-ctu-ubuntu-16.04, docker/dockerfile-build-rocm-terminal, library/CMakeLists.txt, library/src/CMakeLists.txt
- Removing library suffixes, giving cuda builds different package names
- Build both .deb & .rpm's
=> Remove library suffix

library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp
Complex and half functions are not tested or supported. Remove them from hipblas.h and hipblas.cpp
=> remove complex and half functions from API

Jenkinsfile
-  Disable generation of fedora RPM's until such a time as fedora is available
=> ROCm v1.7 does not provide fedora builds

library/src/nvcc_detail/hipblas.cpp
Add HIPBLAS_STATUS_ARCH_MISMATCH  and  CUBLAS_STATUS_ARCH_MISMATCH  to nvcc_detail to support commit below
https://github.com/ROCmSoftwarePlatform/hipBLAS/commit/7715844798a89710f29756519c1d76ae40c1a857
=> add CUBLAS_STATUS_ARCH_MISMATCH

clients/include/testing_nrm2.hpp, clients/include/unit.h
nrm2 has a sqrt operation, so add tolerance to check against cblas result
=> add tolerance for nrm2 tests

install.sh
Too many internal developers ran into our yum -y update forcing its way into upgrading their CentOS 7.4 to 7.5 - without even asking for permission. This has the unfortunate consequence of breaking our own rocm-dkms drivers, in particular amdgpu. On Ubuntu, apt update is needed to refresh the repo database. On CentOS/Fedora, there is no need to do so.
=> Remove unnecessary yum -y update

clients/common/cblas_interface.cpp, clients/common/flops.cpp, clients/common/norm.cpp, clients/common/unit.cpp, library/include/hipblas.h
SWDEV-158256 reports miopen-benchmark build difficulties because of hipBLAS includes the file hip_complex.h. This pull request removes the include for hip_complex.h and comments out all complex code in hipBLAS.
=> comment out complex because hip_complex.h difficulties

clients/gtest/CMakeLists.txt
resolves build failures for hip-clang
-  need to add -lpthread and -lm explicitly for hipblas-test
=> Cmake changes to enable hip-clang to compile

library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp
- Return if hipBLAS handle is null pointer. 
- This prevents memory leak. User must allocate hipBLAS handle pointer.
=> return error if handle is nullptr

library/src/CMakeLists.txt
Fixes cmake issue with ${HIPBLAS_LIBRARIES} environment variable that was previously pointing to libhipblas-targets.so.
=> cmake fix to rocm-export-targets

clients/gtest/CMakeLists.txt, clients/samples/CMakeLists.txt
-  need to add include directory /opt/rocm/hsa/include for file hsa/hsa.h
=> add /opt/rocm/hsa/include to target_include_directories

CMakeLists.txt
resolves #77
Added an option `TRY_CUDA` which, if disabled, will skip the find_package call that enables CUDA
=> Added an option to skip trying to look for CUDA during the build

CMakeLists.txt
- rocBLAS uses c++14. Modify CMakeLists.txt in hipBLAS to use c++14
=> add CMAKE_CXX_STANDARD 14 for c++14 use in rocblas_bfloat16.h

CMakeLists.txt, install.sh
- for hot fix increment the patch number in the version number
- hipBLAS does not have any device code, so use default compiler (c++ on Ubuntu) in place of hcc or hipcc
=> hot_fix: use default compiler like c++ not hcc or hipcc

Jenkinsfile, clients/gtest/CMakeLists.txt, clients/samples/CMakeLists.txt, install.sh
There is no regression in ROCm 2.7 Releas HIP/HCC environment or HIP-Clang environment
when I remove these dependencies on hcc:hc_am.
resolves 201928.
-  Remove dependency on hc_am, which is not needed anymore
=> Remove hipBLAS dependency on hc_am

install.sh
Just to clean up old hip-clang artifacts. We don't need any specific --hip-clang flag since we will use g++ for hipBLAS compilation. Also removing the VERBOSE=1 output.
resolves #N/A
-  Remove --hip-clang flag
-  Remove VERBOSE=1 noise
=> Clean up hip clang install

clients/common/cblas_interface.cpp, clients/common/hipblas_template_specialization.cpp, clients/gtest/blas1_gtest.cpp, clients/include/cblas_interface.h, clients/include/testing_axpy.hpp, clients/include/testing_copy.hpp
Adding missing tests to hipBlas. We already have hipAxpy and hipCopy implemented, but no testing for them. This PR adds testing for these two functions.
=> Add missing tests for BLAS L1

clients/common/cblas_interface.cpp, clients/common/hipblas_template_specialization.cpp, clients/gtest/blas1_gtest.cpp, clients/include/hipblas.hpp, clients/include/testing_iamin.hpp, clients/include/testing_swap.hpp, library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp, library/src/nvcc_detail/hipblas.cpp
Adding (real precision) L1 functions:
- swap
- iamin
iamin is not currently tested as it is still broken in rocBLAS 2.9. Rotation functions (rot(m)(g)) not in rocBLAS 2.9, so not being supported right now. Complex functionality coming in a future PR as well.
=> Adding missing L1 functions

clients/common/cblas_interface.cpp, clients/common/hipblas_template_specialization.cpp, clients/gtest/CMakeLists.txt, clients/gtest/syr_gtest.cpp, clients/gtest/trsv_gtest.cpp, clients/include/cblas_interface.h, clients/include/hipblas.hpp, clients/include/testing_syr.hpp, clients/include/testing_trsv.hpp, clients/include/unit.h, library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp, library/src/nvcc_detail/hipblas.cpp
Adding (real precision) L2 functions:
- syr
- trsv
Complex support will come in another PR. This makes hipBlas support all L2 functions which rocBlas supports.
=> Add missing L2 functions

library/include/hipblas.h
- extend hipblasDatatype_t. Note that there is no additional functions added for the additional datatypes
=> extend enum hipblasDatatype_t

clients/common/hipblas_template_specialization.cpp, clients/gtest/blas1_gtest.cpp, clients/include/hipblas.hpp, clients/include/testing_asum_batched.hpp, clients/include/testing_asum_strided_batched.hpp, clients/include/testing_copy_batched.hpp, clients/include/testing_copy_strided_batched.hpp, clients/include/testing_dot_batched.hpp, clients/include/testing_dot_strided_batched.hpp, clients/include/testing_nrm2_batched.hpp, clients/include/testing_nrm2_strided_batched.hpp, clients/include/testing_scal_batched.hpp, clients/include/testing_scal_strided_batched.hpp, clients/include/testing_swap_batched.hpp, clients/include/testing_swap_strided_batched.hpp, library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp, library/src/nvcc_detail/hipblas.cpp
Sorry for the big PR.
First step to match rocblas 2.10 functionality. Adds:
- scal_batched and scal_strided_batched
- copy_batched and copy_strided_batched
- dot(c)_batched and dot(c)_strided_batched
- swap_batched and swap_strided_batched
- asum_batched and asum_strided_batched
- nrm2_batched and nrm2_strided_batched
Along with corresponding unit tests.
All cuda implementations of L1 batched have been changed to return NOT_SUPPORTED rather than demoting them to non-batched versions.
Most of the changes are testing code changes except for library/src/*/hipblas.cpp and library/include/hipblas.h
A future PR (tomorrow) will include:
- ger_batched and ger_strided_batched
- syr_batched and syr_strided_batched
- gemm_batched and gemm_strided_batched
- complex gemm
- hdot and haxpy, maybe bfdot. …
=> Batched & strided_batched additions

clients/gtest/CMakeLists.txt
resolves #SWDEV-198086
-  add gtest include directory in gtest/CMakeLists.txt
=> Fixed hipBLAS build failure due to missing gtest include directory

library/CMakeLists.txt
ROCm3.0 is changing the name of hip_hcc to hip-hcc. Changing the dependency to rocm-dev will allow us to support current and future package names.
=> Changing package dependency to rocm-dev

clients/common/cblas_interface.cpp, clients/common/flops.cpp, clients/common/hipblas_template_specialization.cpp, clients/common/near.cpp, clients/common/norm.cpp, clients/common/unit.cpp, clients/common/utility.cpp, clients/gtest/blas1_gtest.cpp, clients/gtest/gemm_batched_gtest.cpp, clients/gtest/gemm_gtest.cpp, clients/gtest/gemm_strided_batched_gtest.cpp, clients/gtest/gemv_batched_gtest.cpp, clients/gtest/gemv_gtest.cpp, clients/gtest/gemv_strided_batched_gtest.cpp, clients/include/testing_nrm2.hpp, clients/include/testing_nrm2_batched.hpp, clients/include/testing_nrm2_strided_batched.hpp, clients/include/utility.h, library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp, library/src/nvcc_detail/hipblas.cpp
- The names hipComplex and hipDoubleComplex are defined in /opt/rocm/include/hip/hip_complex.h .
- To avoid HIP versus hipBLAS name conflicts, change hipBLAS to use hipblasComplex and hipblasDoubleComplex
=> hipComplex -> hipblasComplex, hipDoubleComplex -> hipblasDoubleComplex

clients/gtest/CMakeLists.txt, clients/samples/CMakeLists.txt, install.sh
- New mode of building is added "-r,--relocatable" which is used
for ROCm stack installed in /opt/rocm-ver.
- Below CMAKE parameters are set/overwritten in above mode
CMAKE_INSTALL_PREFIX
CMAKE_PREFIX_PATH
CMAKE_SHARED_LINKER_FLAGS
ROCM_DISABLE_LDCONFIG
ROCM_PATH
Signed-off-by: Pruthvi Madugundu <pruthvigithub@gmail.com>
=> hipBLAS changes to support multiple ROCM installation

clients/gtest/CMakeLists.txt, clients/samples/CMakeLists.txt, install.sh
- New mode of building is added "-r,--relocatable" which is used
for ROCm stack installed in /opt/rocm-ver.
- Below CMAKE parameters are set/overwritten in above mode
CMAKE_INSTALL_PREFIX
CMAKE_PREFIX_PATH
CMAKE_SHARED_LINKER_FLAGS
ROCM_DISABLE_LDCONFIG
ROCM_PATH
Signed-off-by: Pruthvi Madugundu <mpruthvi@gmail.com>
=> hipBLAS changes to support multiple ROCM installation (#126)

clients/include/testing_asum_strided_batched.hpp, clients/include/testing_gemm.hpp, clients/include/testing_gemm_batched.hpp, clients/include/testing_gemm_ex.hpp, clients/include/testing_ger_batched.hpp, clients/include/testing_rot.hpp, clients/include/testing_rot_batched.hpp, clients/include/testing_rot_strided_batched.hpp, clients/include/testing_rotg_batched.hpp, clients/include/testing_rotg_strided_batched.hpp, clients/include/testing_rotm.hpp, clients/include/testing_rotm_batched.hpp, clients/include/testing_rotm_strided_batched.hpp, clients/include/testing_rotmg_batched.hpp, clients/include/testing_rotmg_strided_batched.hpp, clients/include/testing_syr_batched.hpp, clients/include/utility.h
Fix for SWDEV-213043:
- Fixes memory leaks in testing involving not calling hipblasDestroy(handle)
- Fixed error in utility.h where nothing was returned in the random number generators
=> Fix for SWDEV-213043

clients/common/hipblas_template_specialization.cpp, clients/gtest/CMakeLists.txt, install.sh
The hipblastrmm_matrix_size/trmm_gtest tests seg fault when building with --clang. Unsure how to fix this, as the loop is unable to be unrolled, and functionality is broken.
=> Add --clang option and enable -f16c

CMakeLists.txt, library/CMakeLists.txt, library/src/CMakeLists.txt
Addresses [SWDEV-225175](http://ontrack-internal.amd.com/browse/SWDEV-225175).
Takes the proposed fixes in the ticket and implements them. Seems to work when building on a cuda machine using ./install.sh --cuda. There are still some issues building the client on cuda, will address these in another PR.
I know Fei is working on hipFFT and was mentioning improvements in the build system. At a later time it's probably a good idea to have these libraries have similar build systems (hipFFT, hipSPARSE, hipBLAS, etc.), but I'm probably not the best person to take the lead on that since I lack experience in cmake, but I'm always willing to help!
=> Fixing cuda build.

clients/gtest/gemm_ex_gtest.cpp, clients/include/testing_gemm_ex.hpp, library/src/hcc_detail/hipblas.cpp, library/src/nvcc_detail/hipblas.cpp
Problem: hipBLAS clients didn't work when building on CUDA. This was because we were attempting to test `gemmEx` which wasn't implemented for CUDA.
Fix: Implement `gemmEx` for CUDA. Note that `gemmEx` is only available in CUDA for compute capabilities >= 5.0. We do not check for this, it will just return `HIPBLAS_STATUS_ARCH_MISMATCH`.
Small changes to gemmEx testing to ensure that `HIPBLAS_STATUS_SUCCESS` was returned from `gemmEx`. If not, we check that `HIPBLAS_STATUS_ARCH_MISMATCH` was returned instead. Could fix this in the future to ensure that when `ARCH_MISMATCH` is returned, the compute capability is _actually_ < 5.0 and is a CUDA device.
=> Cuda fixes

library/include/hipblas.h
- Remove unnecessary `auto` return type as only C++14 starts to deduce
that automatically. As that header would be included in other
projects, that unnecessary dependency should be removed or
internalized.
resolves #___
-
-
-
=> Make the return type explicit.

CMakeLists.txt, clients/gtest/CMakeLists.txt, library/src/CMakeLists.txt
Cherry-pick [PR#199](https://github.com/ROCmSoftwarePlatform/hipBLAS/pull/199)
=> Use add_definitions( -D__HIP_PLATFORM_SOLVER__ ) for hipBLAS directory and below, rather than for each individual target

clients/include/utility.h, library/include/hipblas.h
The C++ standard is ambiguous; there are many conflicting specs:
1. A `constexpr` or `const` _non-template_ variable has _internal linkage_, unless declared `extern`.
2. A `constexpr` or `const` _template_ variable has _external linkage_, unless declared `static`.
3. In C++17, a `constexpr` variable is implicitly `inline`; in C++14, variables cannot be `inline`. `inline` variables can be defined in multiple compilation units without violating ODR. Some compilers treat C++14 `constexpr` variables as `inline` even though C++14 does not recognize `inline` variables.
4. A template specialization is not allowed to have a _storage class specifier_ like `static`, but it is unclear whether this was intended to apply to variable templates, or whether _storage class specifier_ and _linkage_ are …
=> Make constexpr variable specializations static, to satisfy ODR

clients/common/utility.cpp, clients/gtest/geqrf_batched_gtest.cpp, clients/gtest/geqrf_gtest.cpp, clients/gtest/geqrf_strided_batched_gtest.cpp, clients/gtest/getrf_batched_gtest.cpp, clients/gtest/getrf_gtest.cpp, clients/gtest/getrf_strided_batched_gtest.cpp, clients/gtest/getrs_batched_gtest.cpp, clients/gtest/getrs_gtest.cpp, clients/gtest/getrs_strided_batched_gtest.cpp, clients/include/testing_geqrf.hpp, clients/include/testing_geqrf_batched.hpp, clients/include/testing_geqrf_strided_batched.hpp, clients/include/testing_getrf.hpp, clients/include/testing_getrf_batched.hpp, clients/include/testing_getrf_strided_batched.hpp, clients/include/testing_getrs.hpp, clients/include/testing_getrs_batched.hpp, clients/include/testing_getrs_strided_batched.hpp, clients/include/utility.h, library/src/hcc_detail/hipblas.cpp
Added complex support for geqrf functions and removed obsolete use of USE_DEVICE_MODE macro. geqrf_batched can now call geqrf_ptr_batched in rocSOLVER, which matches the cuBLAS method signature.
=> rocSOLVER support 2

install.sh, library/src/CMakeLists.txt
[SWDEV-235957](http://ontrack-internal.amd.com/browse/SWDEV-235957)
Adds --rocblas-path command line option to choose a path to a pre-built rocblas to use. If a rocblas install cannot be found at that path, the regular search continues, and will find the installed rocblas in /opt/rocm.
=> Adding rocblas_path build variable for custom rocblas path.

.githooks/pre-commit
Make clang-format use `PATH` and use it if it's available. This is necessary because of the HCC->hip-clang change.
=> Use PATH and robustly test for clang-format

clients/gtest/dgmm_gtest.cpp, clients/include/hipblas_vector.hpp, clients/include/testing_dgmm.hpp, clients/include/testing_dgmm_batched.hpp, clients/include/testing_dgmm_strided_batched.hpp, clients/include/testing_geqrf.hpp, clients/include/testing_geqrf_batched.hpp, clients/include/testing_geqrf_strided_batched.hpp, clients/include/testing_getrf.hpp, clients/include/testing_getrf_batched.hpp, clients/include/testing_getrf_strided_batched.hpp, clients/include/testing_getrs.hpp, clients/include/testing_getrs_batched.hpp, clients/include/testing_getrs_strided_batched.hpp
Resolves [LWPMLSE-62](http://ontrack-internal.amd.com/browse/LWPMLSE-62).
Hotfix for hipBLAS. Since rocBLAS was fixed, hipBLAS was failing since I didn't disable dgmm_batched and dgmm_strided_batched tests, they were still enabled with incorrect reference code.
This enables all dgmm tests and fixes the reference code. Passed on CUDA, haven't tested on hip so hopefully this works on CI.
=> Hotfix: dgmm test fix

clients/common/cblas_interface.cpp, clients/gtest/gemm_ex_gtest.cpp, clients/include/cblas_interface.h, clients/include/testing_gemm_batched.hpp, clients/include/testing_gemm_batched_ex.hpp, clients/include/testing_gemm_ex.hpp, clients/include/testing_gemm_strided_batched_ex.hpp, clients/include/testing_getrs.hpp, clients/include/testing_getrs_batched.hpp, clients/include/testing_getrs_strided_batched.hpp, clients/include/testing_tpsv.hpp, clients/include/testing_tpsv_batched.hpp, clients/include/testing_tpsv_strided_batched.hpp, clients/include/testing_trsv.hpp, clients/include/testing_trsv_batched.hpp, clients/include/testing_trsv_strided_batched.hpp, clients/include/utility.h, library/src/hcc_detail/hipblas.cpp, library/src/nvcc_detail/hipblas.cpp
- Added missing conversion functions for these types in hipblas:
- `HIPBLAS_R_8I`
- `HIPBLAS_R_32I`
This enables support for some additional gemmEx functions which we support in rocBLAS (mainly i8/i32 mixed precision).
- Added missing tests for complex gemmEx
- Added missing tests for i8/i32 gemmEx
Most of the changes here are incidental from changing the cblas interface. I tried to make few changes in the testing code since this is going to master, but the gemm testing can definitely be cleanup up quite a bit later.
Also apparently in cublas before v10, gemmEx only supports alpha, beta = 0 or 1 for i8/i32 precision. Also that precision isn't supported in their batched versions.
=> Missing types master

library/src/hcc_detail/hipblas.cpp
With the size of rocBLAS's default device memory allocation increased to 32 MB, we don't really need to allocate a different default in hipBLAS.
=> Remove setting a different default device memory size

docker/dockerfile-install-ubuntu, install.sh
- According to debian standards, package name and package
version should be seperated by '_'.
- Changes to support rocm-cmake https://github.com/RadeonOpenCompute/rocm-cmake/pull/38
=> Updates to debian package name

clients/include/argument_model.hpp
The time taken to run a benchmark is now the average over all iterations, rather than the cumulative sum.
=> Divide time by iterations in bench logging

CMakeLists.txt, library/CMakeLists.txt, library/src/CMakeLists.txt
After removing all rocm libraries, and installing hip-nvcc, this seems to work on a CUDA machine, tests are currently running. This seems to be consistent with hipSPARSE for the most part. @YvanMokwinski if you notice anything that drastically differs, let me know!
Sidenote: The dependency installation seems to be weird on my CUDA machine, I had to do a small workaround to get them to be found, I'll look into this tomorrow, but it's unrelated to this PR.
=> Removing rocm dependency for CUDA builds

CHANGELOG.md, clients/common/norm.cpp, docker/dockerfile-build-nvidia-cuda
Related to https://github.com/ROCmSoftwarePlatform/rocSOLVER/pull/188
The method signature for caxpy in norm.cpp had alpha as a float, whereas the LAPACK signature has alpha as a single complex. A similar error affects the norm.cpp version of zaxpy.
A separate fix has dockerfile-build-nvidia-cuda point to hipBLAS directories, rather than rocBLAS.
=> Fixed erroneous caxpy and zaxpy method signatures

clients/include/d_vector.hpp, clients/include/device_batch_vector.hpp, clients/include/hipblas_vector.hpp, clients/include/host_batch_vector.hpp, clients/include/testing_scal_batched.hpp
This adds the `host_batch_vector` and `device_batch_vector` implementations from rocBLAS. I've updated the implementation of scal_batched tests to the intended use. I will update all other tests in another PR to keep this one moderately small and easy to review.
=> Adding updated batched vectors for tests - only on scal

clients/include/testing_nrm2.hpp, clients/include/testing_nrm2_batched.hpp, clients/include/testing_nrm2_batched_ex.hpp, clients/include/testing_nrm2_ex.hpp, clients/include/testing_nrm2_strided_batched.hpp, clients/include/testing_nrm2_strided_batched_ex.hpp, clients/include/unit.h
Matching rocBLAS tolerance checking for nrm2.
See discussion [here](https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/pull/366#discussion_r504300139).
=> Updating nrm2 tolerance code

scripts/performance/blas/commandrunner.py, scripts/performance/blas/getspecs.py, scripts/performance/blas/performancereport.py
This adds the following features to the hipBLAS performance scripts:
- Allows performance scripts to be ran on CUDA machines.
- Allows the creation of efficiency plots (this takes GFLOPS and compares it to the theoretical max for GFLOPS)
- Allows 2 runs to be compared on the same plot. Currently this is solely to compare a single run to an already-completed run from a CUDA machine. This can be expanded in the future if people are interested in comparing other data.
I've also opened [this ticket](http://ontrack-internal.amd.com/browse/LWPMLSE-102) to clean up some of the performance plotting code.
Note that I'm the only one that's currently using these scripts and that the changes to them are ongoing, they still need a lot of improvement, but these changes currently work for my needs.
=> Add features to performance scripts

clients/common/norm.cpp
Porting bug fix from https://github.com/ROCmSoftwarePlatform/rocSOLVER/pull/196.
Some norm_check_general methods can segfault if called with a matrix pointer that has had an offset applied.
=> Fixed potential segfault in norm.cpp

clients/include/testing_gemm.hpp, clients/include/testing_gemm_batched.hpp, clients/include/testing_gemm_strided_batched.hpp
Previously wasn't handling this correctly, the simple cast doesn't work as expected. This matches gemm_ex tests for now. Also it doesn't look like we have tests for a non-zero imaginary part for cgemm/zgemm, I'll make a ticket for this.
=> Fixing half-precision alpha for gemm tests.

CMakeLists.txt, clients/benchmarks/CMakeLists.txt, clients/gtest/CMakeLists.txt, clients/samples/CMakeLists.txt, install.sh, library/CMakeLists.txt, library/src/CMakeLists.txt
Detection of whether HIP uses HCC or NVCC should really be improved, but I leave that up to AMD.
How it's done here with `USE_CUDA=ON` by default, and then
```
if( NOT CUDA_FOUND )
target_compile_definitions( hipblas-bench PRIVATE __HIP_PLATFORM_HCC__ )
```
is really poor practice, cause you can have a system CUDA install but still have HIP configured with HCC.
Please just infer from the HIP config file if the compiler is HCC or NVCC, don't assume "if the user has CUDA they likely want CUDA".
Thanks!
=> Don't look for CUDA by default

CHANGELOG.md, clients/common/utility.cpp, clients/include/testing_gemm_batched_ex.hpp, clients/include/testing_gemm_ex.hpp, clients/include/testing_gemm_strided_batched_ex.hpp, clients/include/utility.h, library/src/hcc_detail/hipblas.cpp
Updating hipBLAS to work correctly with the new rocBLAS gemm_ex.
- When calling hipblasGemmEx with a rocBLAS backend, we now query the preferable data format for the architecture. This preferred data format is then passed into the call for rocblas_gemm_ex.
- Slight additions were needed to be able to query the architecture from hipBLAS clients to get our tests to work. Note I haven't tested this on gfx908 yet, will wait for CI.
The changes to the testing infrastructure (that is, adding the architecture query) is needed as we are not exposing the rocblas_query API function in hipBLAS with this PR. Any user that is building a program to run on multiple architectures will have to do something similar, unless we decide to expose the query API in hipBLAS as well.
=> Updating int8 gemm_ex

clients/gtest/trmm_gtest.cpp, clients/include/bytes.hpp, clients/include/flops.hpp
Matching trmm flop calculations from http://www.netlib.org/blas/sblas3time.f. See #311 for some discussion.
=> trmm legacy flop calculations

clients/include/testing_nrm2_batched.hpp
Removed hipblasDestroy() calls, but didn't update to new handle, causing a memory leak. This should fix that.
=> Fix for nrm2_batched test

clients/benchmarks/client.cpp, clients/common/cblas_interface.cpp, clients/gtest/blas1_gtest.cpp, clients/include/argument_model.hpp, clients/include/bytes.hpp, clients/include/flops.hpp, clients/include/testing_rot.hpp, clients/include/testing_rot_batched.hpp, clients/include/testing_rot_strided_batched.hpp, clients/include/testing_rotg.hpp, clients/include/testing_rotg_batched.hpp, clients/include/testing_rotg_strided_batched.hpp, clients/include/testing_rotm.hpp, clients/include/testing_rotm_batched.hpp, clients/include/testing_rotm_strided_batched.hpp, clients/include/testing_rotmg.hpp, clients/include/testing_rotmg_batched.hpp, clients/include/testing_rotmg_strided_batched.hpp, clients/include/type_dispatch.hpp
I've made some changes in ArgumentModel to handle rot(m)g cases where there are no arguments being passed in. It seems to work ok, but if anyone has Parameter Pack experience, they might want to weight in.
=> Updating rot(m)(g) tests

library/include/exceptions.hpp, library/include/hipblas.h, library/src/hcc_detail/hipblas.cpp, library/src/hipblas_auxiliary.cpp, library/src/hipblas_module.f90, library/src/nvcc_detail/hipblas.cpp
Adding `catch`s to hipBLAS as discussed.
- introduces `HIPBLAS_STATUS_INVALID_ENUM`. If we don't want this, we can expand the definition of `HIPBLAS_STATUS_INVALID_VALUE`, but I prefer adding this additional status
- Instead of throwing strings in failed conversions, we now throw this status.
- Adding `exception_to_hipblas_status` (same as in rocBLAS)
- Added `try` `catch` blocks to hcc gbmv. Tested this out in hipblas-bench with a non-existent transpose type, seemed to work as expected.
The `try` `catch` blocks will have to be added to all hcc and nvcc functions. I'll see if I can do a simple find & replace to avoid some tedious work :)
=> Improving exception handling

clients/benchmarks/client.cpp, clients/benchmarks/program_options.hpp
Ports changes to program_options.hpp from https://github.com/ROCmSoftwarePlatform/rocSOLVER/pull/229.
This expands the emulated boost functionality by turning variables_map into a map of variable_value objects rather than a set of strings, as well as allowing value objects to be constructed without a pointer.
These changes are currently unneeded by hipBLAS, but could be useful later. For example, in rocSOLVER, we use the information provided by the variables_map to auto-generate strides and leading dimension values if they have not been provided by the user, ensuring that hard-coded defaults do not cause bench client failures.
=> Improved boost emulation

clients/include/testing_dot_strided_batched.hpp
This is similar to rocBLAS-internal PR#631
- used the following docker container, this is the same as the docker container used by CI: compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-rel-4.2:10-STG1
- The /opt/rocm/llvm/bin/clang-format in this docker has changed
- Ran the following command to update formatting for this docker: git ls-files -z *.cc *.cpp *.h *.hpp *.cl *.h.in *.hpp.in *.cpp.in | xargs -0 /opt/rocm/llvm/bin/clang-format -style=file -i
=> clang-format changes for ROCm 4.2 /opt/rocm/llvm/bin/clang-format

library/src/hcc_detail/hipblas.cpp
getri_outofplace_batched will be added to rocSOLVER's public API in 4.3 by https://github.com/ROCmSoftwarePlatform/rocSOLVER/pull/243. This PR removes the declarations that were needed because of it not being part of the public API.
=> Removed getri_outofplace_batched declaration

.jenkins/precheckin-cuda.groovy
Our CI system needs to build the hipBLAS packages that support the CUDA backend.
=> Adding CUDA packaging in CI

clients/include/testing_gemv.hpp, clients/include/testing_gemv_batched.hpp, clients/include/testing_gemv_strided_batched.hpp, clients/include/testing_hemv.hpp, clients/include/testing_hemv_batched.hpp, clients/include/testing_hemv_strided_batched.hpp
In large matrices `int index = n*lda` exceeds `int` 31 bit datatype capacity which results in a `std::bad_alloc` error. Therefore, change to use `size_t` in place of `int` for index in Level 2 BLAS gemv and hemv.
=> Add size_t to gemv and hemv

CHANGELOG.md, CMakeLists.txt, library/src/CMakeLists.txt
Switch installation to use `rocm_install` in place of `install` for development packages.
Update rocm-cmake to required version. In order for CMake to detect the version, rocm-cmake must be built and installed, here to a temporary directory.
=> Setup runtime and development packages

clients/gtest/gemm_ex_gtest.cpp, clients/gtest/nrm2_ex_gtest.cpp, clients/include/testing_nrm2_batched_ex.hpp, clients/include/testing_nrm2_ex.hpp, clients/include/testing_nrm2_strided_batched_ex.hpp, clients/include/unit.h
Seeing if this will remove the failures from [SWDEV-300988](https://ontrack-internal.amd.com/browse/SWDEV-300988).
It appears that the cpu result on windows is off by 1 from the cpu result we are getting on linux for this specific half-precision test case. I believe this is due to the conversion from hipblasHalf -> float -> hipblasHalf during the cpu calculations. This differs from the rocBLAS implementation as rocBLAS uses _Float16, which apparently isn't defined for g++ (see [here](https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/commit/5c144635b237cd0e0f96e2895a835317ce52e68c#diff-972107ba5a8a0ad89499e64ffa0d015ffc0d59e9379b265d947904b13f4181a2R49)).
If anyone has any ideas for a better solution, I'm all ears! I can work on getting _Float16 to work with hipcc in the meantime.
=> Nrm2_ex windows failures

clients/include/testing_asum.hpp, clients/include/testing_asum_batched.hpp, clients/include/testing_asum_strided_batched.hpp, clients/include/testing_axpy.hpp, clients/include/testing_axpy_batched.hpp, clients/include/testing_axpy_strided_batched.hpp, clients/include/testing_copy.hpp, clients/include/testing_copy_batched.hpp, clients/include/testing_copy_strided_batched.hpp
Moving hipBLAS test calls into `if(unit_check || norm_check)`. I don't see any use of making these calls unless we're testing the output, it should save some slight time when running benchmarks. This could be done to rocBLAS as well.
I've only done this for a few L1s to get feedback, if it's agreed upon I'll change all unit tests to use this. Also made some other small fixes along the way that I noticed.
=> Moving test calls into if statement

clients/benchmarks/client.cpp, clients/gtest/getrf_batched_gtest.cpp, clients/gtest/getrf_gtest.cpp, clients/gtest/getrf_strided_batched_gtest.cpp, clients/gtest/getri_batched_gtest.cpp, clients/include/testing_getrf_npvt.hpp, clients/include/testing_getrf_npvt_batched.hpp, clients/include/testing_getrf_npvt_strided_batched.hpp, clients/include/testing_getrf_strided_batched.hpp, clients/include/testing_getri_npvt_batched.hpp
_Should_ be the final additions to hipblas-bench unless more functions are added.
Remaining work in hipblas tests:
- allow negative incx/incy
- bad enum test ([LWPMLSE-122](https://ontrack-internal.amd.com/browse/LWPMLSE-122))
=> Adding npvt solver tests to hipblas-bench

clients/include/flops.hpp, clients/include/testing_ger.hpp, clients/include/testing_ger_batched.hpp, clients/include/testing_ger_strided_batched.hpp
This PR modifies the GFLOPs calculation of hipBLAS level 2 functions to be identical to level 2 rocBLAS functions.
=> Modify hipBLAS level2 BLAS GFLOPs

CHANGELOG.md, clients/gtest/hipblas_gtest_main.cpp, clients/include/utility.h, library/include/hipblas-version.h.in
- Print hipblas version and device info in hipblas-test
- Remove redundant include guard
- Fix typo in hipblasVersionMinor
Related PR: https://github.com/ROCmSoftwarePlatform/hipSOLVER/pull/59
=> Print version info in hipblas-test

clients/benchmarks/CMakeLists.txt, clients/gtest/CMakeLists.txt
When putting together https://github.com/spack/spack/pull/27074, I noticed that hipblas-test can end up missing some blas symbols. I patched it in Spack, but I figured I should probably make the change here, too.
While I was at it, I figured I'd make a couple other changes to clean up the clients build:
- Simplify CMake using REQUIRED
- Cleanup GTest in clients
- Ensure that blas is linked
- Consolidate hipblas-bench target properties
=> Clients CMake cleanup

clients/benchmarks/CMakeLists.txt, clients/gtest/CMakeLists.txt
resolves SWDEV-311824
- This removes an error where the compile for cblas_interface.cpp cannot locate the file cblas.h
- It adds CBLAS_INCLUDE_DIRS to the hipblas_bench target include directories
=> addd cblas include directory to hipblas-bench include directory

install.sh
- For  SWDEV-311824  cmake3.20.2 is being installed to replace the existing cmake. 
- This change should prevent this reinstall of a more recent version of cmake. This is similar to rocBLAS-internal PR 616
- This PR has only been tested manually on ubuntu. The CI will be used to test on other Linux distributions.
=> remove cmake3 and cmake dependency from install.sh

docs/source/functions.rst, library/include/hipblas.h
Add doxygen grouping to hipblas.h through the use of @{ and @} markers.
=> Doxygen grouping in hipBLAS

CHANGELOG.md
Following the instructions for [changelog updates](https://confluence.amd.com/display/MLSE/Changelogs+and+Release+Notes), I updated the changelog on release branch 5.0. I accidentally committed directly to the release branch rather than my fork and creating a PR. The only change was to CHANGELOG.md so I think it should be fine, but let me know if either of you disagree. This PR is for the merge back into develop.
=> Merge back changelog hotfix for ROCm 5.0

clients/gtest/gemm_ex_gtest.cpp, library/src/hcc_detail/hipblas.cpp
Potential fix for SWDEV-315039.
It looks like the batched versions of gemm_ex int8 fail on some architectures as they do not query the gemm flag for rocBLAS. This PR hopefully fixes that, and adds back tests for int8. Currently aimed at a master hotfix as I didn't find the problem until after I finished feature complete, unfortunately. Will have to wait for CI to ensure this works on all architectures, including cuBLAS backend.
=> Batched gemmEx int8 fix

README.md
This PR addresses the issue reported in \[Issues\#454\]\(https://github.com/ROCmSoftwarePlatform/hipBLAS/issues/454\)
\- changed 'rocblas' to 'hipblas'
=> Fix for broken link in README file

library/CMakeLists.txt
This is an autogenerated PR.
This is intended to pull any hotfixes for ROCm release 5.0 (including changelogs and documentation) back into develop.
=> Hotfixes from release/rocm-rel-5.0 at release 5.0

CMakeLists.txt, install.sh
- removed installation of cuda when passing in `-d` to install script. We aren't installing rocBLAS/rocSOLVER when passing in this flag either. It seems dangerous to do this as it will update cuda, even if it is already installed - users may not want this
- adds `--cudapath` to allow user to specify which cuda build they want to use (default to `/usr/local/cuda`. I've tested with a couple `/usr/local/cuda-VER` and it seems to work as expected)
- adds `--installcuda` to install cuda package via package manager, simply `apt install cuda` or similar
- adds `--installcudaversion` to be used with `--installcuda` to specify which version of cuda to install, for example: `./install.sh --cuda --installcuda --installcudaversion 11.4` will install cuda v11.4 using package manager
Tested flags on …
=> Cuda install flags

install.sh
Same changes as in https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/pull/1204
- Didn't change the `install_pkgmanager_packages_version()` method I introduced previously as it's only used to install `cuda` for now, can update in the future if needed.
- Added gcc-fortran dependency to sles as it's needed
- Ran into the same devtoolset-7-gcc-gfortran / gcc-gfortran dependency issue on centos7 as mentioned in the rocBLAS PR, can discuss in a meeting
=> Installing dependencies in one call

clients/gtest/dgmm_gtest.cpp, clients/gtest/gbmv_batched_gtest.cpp, clients/gtest/gbmv_strided_batched_gtest.cpp, clients/gtest/gemv_batched_gtest.cpp, clients/gtest/gemv_strided_batched_gtest.cpp, clients/gtest/hbmv_gtest.cpp, clients/gtest/hemm_gtest.cpp, clients/gtest/hemv_batched_gtest.cpp, clients/gtest/hemv_strided_batched_gtest.cpp, clients/gtest/hpmv_gtest.cpp, clients/gtest/symm_gtest.cpp
Removing some tests from hipBLAS, these changes make it take about half the time on my vega20 compared to previously. Windows tests have been taking a long time, this is some low hanging fruit to try to reduce that.
This is mostly reducing batched tests which took longer than expected. We don't need to do exhaustive testing here because the backends themselves should ensure their own correctness.
See LWPMLSE-232 for more info on test timing.
=> Reducing test time

scripts/performance/blas/combine_plots.py
Adding a script which can be used with performance data from performancereport.py to plot the performance of multiple runs of different functions together. See LWPMLSE-253 for some example plots created with this script.
Example usage:
`./combine_plots.py -d output1/run00 -d output2/run00`
where output1 and output2 are directories containing the output from a performancereport.py run. Or the directories could be manually created with just the input/output from hipblas-bench command line runs.
=> Adding a script to plot multiple performance runs together

install.sh
When `"$VERSION_ID" == "8.6"` or `"$VERSION_ID" == "9"`, hipBLAS should install the latest CentOS / RHEL dependencies.
Ticket: SWDEV-338310
=> Fix RHEL 8 and 9 client dependencies

scripts/performance/blas/commandrunner.py
resolves # LWPMLSE-317
ROCm 5.2 has adopted new Linux filesystem hierarchy.
rocm_smi.py and rsmiBindings.py files are moved to /opt/rocm/libexec/rocm_smi directory for ROCm 5.2 and above.
- Update the rocm-smi path based on ROCm version.
For ROCm version below 5.2 , install_path will be /opt/rocm/bin
For ROCm version 5.2 and above, install_path will be /opt/rocm/libexec/rocm_smi
=> Fix rocm-smi path for ROCm 5.2 and above

clients/common/near.cpp, clients/include/near.h, clients/include/testing_dot_batched_ex.hpp, clients/include/testing_dot_ex.hpp, clients/include/testing_dot_strided_batched_ex.hpp
Some dot_ex tests failed while testing out gfx11. It appears that it's just a conversion from fp16->fp32->fp16->fp32 which is causing the issue. Only seen when the result is 0, we get a cpu result of 0 and a gpu result of (very small number). I added some example output at SWDEV-333517.
This change dot_ex tests to use near_check rather than unit_check for half precision. Using a tolerance of epsilon * N.
=> Change dot_ex tests to use near_check for fp16

clients/gtest/geqrf_batched_gtest.cpp, clients/gtest/geqrf_gtest.cpp, clients/gtest/geqrf_strided_batched_gtest.cpp, clients/include/testing_geqrf.hpp, clients/include/testing_geqrf_batched.hpp, clients/include/testing_geqrf_strided_batched.hpp, library/src/amd_detail/hipblas.cpp
SWDEV-344553
- geqrf (and batched variants) will now return info = 0 when nullptrs are passed in with either n == 0 || m == 0. Note that batch_count == 0 will return bad info if a nullptr is passed in
- added some tests to tests this case and other bad input cases
TODO:
- the test suite is still not thorough, should add bad_args or something similar to rocBLAS as we aren't testing all cases for nullptrs, just added some ad-hoc testing for this fix
- will go through other rocSOLVER functions as this fix is probably needed in other places. Just wanted this to be ready quick/put in separately in case needed for a hotfix
=> Fixing geqrf return status for nullptrs, updating tests

clients/gtest/gels_batched_gtest.cpp, clients/gtest/gels_gtest.cpp, clients/gtest/gels_strided_batched_gtest.cpp, clients/gtest/geqrf_batched_gtest.cpp, clients/gtest/geqrf_gtest.cpp, clients/gtest/geqrf_strided_batched_gtest.cpp, clients/gtest/getrs_batched_gtest.cpp, clients/gtest/getrs_gtest.cpp, clients/gtest/getrs_strided_batched_gtest.cpp, clients/include/testing_gels.hpp, clients/include/testing_gels_batched.hpp, clients/include/testing_gels_strided_batched.hpp, clients/include/testing_geqrf.hpp, clients/include/testing_geqrf_batched.hpp, clients/include/testing_geqrf_strided_batched.hpp, clients/include/testing_getrs.hpp, clients/include/testing_getrs_batched.hpp, clients/include/testing_getrs_strided_batched.hpp, library/include/hipblas.h, library/src/amd_detail/hipblas.cpp
Updating info codes in solver-based functions (based off of solver argument checking code). Adding bad_arg tests for solver functions to ensure we're testing the hipBLAS portion of the code.
getrs
-------
- A and ipiv can be nullptr if n == 0
- B can be nullptr if n == 0 || nrhs == 0
- info = -1 if transpose != N || T || C
gels
-----
- A can be nullptr if n == 0 || m == 0
- B can be nullptr if nrhs == 0 || (m == 0 && n == 0)
- info = -1 if transpose != N || T for real cases, or transpsoe != N || C for complex cases
- deviceInfo can be nullptr if batchCount == 0
Aside from deviceInfo in gels, batchCount == 0 doesn't skip any other checks, it looks like this is the case in argument checking in rocSOLVER.
=> solver function argument checking

library/include/hipblas.h
* matches rocBLAS fix for Visual Studio compiler support
=> add MSVC deprecation form

LICENSE.md, library/include/hipblas-version.h.in
There's nothing wrong with the include guards in hipBLAS, but the version guard does use a slightly different pattern than the other headers. I figured it might be nice to make it consistent.
=> Minor tweak to include guards for consistency

library/include/hipblas.h, library/src/amd_detail/hipblas.cpp, library/src/nvidia_detail/hipblas.cpp
resolves #[LWPMLSE-343](https://ontrack-internal.amd.com/browse/LWPMLSE-343) and issue [#543](https://github.com/ROCmSoftwarePlatform/hipBLAS/issues/543)
- Add const qualifier to hipBLAS functions swap, sbmv, spmv, symv, trsm.
=> Add const qualifier to hipBLAS functions

clients/common/utility.cpp, clients/gtest/gemm_ex_gtest.cpp, clients/include/testing_gemm_batched_ex.hpp, clients/include/testing_gemm_ex.hpp, clients/include/testing_gemm_strided_batched_ex.hpp, clients/include/utility.h, library/include/hipblas.h, library/src/amd_detail/hipblas.cpp, library/src/hipblas_module.f90, library/src/nvidia_detail/hipblas.cpp
Removes support for:
- `hipblasInt8Datatype_t` enum
- `hipblasSetInt8Datatype`
- `hipblasGetInt8Datatype`
- related internal functions
Removes testing, and removes some documentation. Will add in CHANGELOG at FC unless there's somewhere better to include this (deprecation.rst?)
=> Removing support for packed int8

clients/samples/example_hgemm.cpp, clients/samples/example_hgemm_hip_half.cpp, clients/samples/example_sgemm.cpp, clients/samples/example_sgemm_strided_batched.cpp, clients/samples/example_strmm.cpp
- small correction in samples code to change CHECK_HIPBLAS_ERROR macro from printing rocBLAS to print hipBLAS
=> correct CHECK_HIPBLAS_ERROR macro to print hipBLAS in place of rocBLAS

clients/gtest/CMakeLists.txt
* avoids copying in extra rocm math libs which may contaminate local build
=> don't copy extra dlls

.jenkins/multicompiler.groovy, .jenkins/precheckin.groovy, .jenkins/staticlibrary.groovy
The rocSOLVER library has added a dependency on rocSPARSE, so it may be required to successfully link with rocSOLVER.
=> Add rocSPARSE dependency to math-ci

CHANGELOG.md
Looks like not really any changes for hipBLAS this release.
https://github.com/rocmsoftwareplatform/hipblas/compare/release/rocm-rel-5.6...develop
=> Updating changelog for rocm 5.7

clients/include/utility.h, clients/samples/example_c.c, clients/samples/example_hgemm.cpp, clients/samples/example_hgemm_hip_half.cpp, clients/samples/example_hip_complex_her2.cpp, clients/samples/example_sgemm.cpp, clients/samples/example_sgemm_strided_batched.cpp, clients/samples/example_sscal.cpp, clients/samples/example_strmm.cpp
Users of hipBLAS should be including the header as <hipblas/hipblas.h>, so it is nice to use that style of include in the samples.
=> Use new-style includes in samples
